### ISSUE TITLE
Bug when dealing with nvec < 3

### ISSUE THREAD

**Issue by matt-chan** [theochem/cellcutoff#25]
Hi @tovrstra, is this a bug?

https://github.com/theochem/cellcutoff/blob/67205f0c85ac585c44fc738fcbd7bd9af2f0d7e9/python-cellcutoff/cellcutoff/ext.pyx#L88-L89

It always copies nine elements, even if nvec is less than 3. I think this will end up giving garbage data at some point? The constructor allows for vec smaller than (3,3) if you provide one yourself. 

https://github.com/theochem/cellcutoff/blob/67205f0c85ac585c44fc738fcbd7bd9af2f0d7e9/python-cellcutoff/cellcutoff/ext.pyx#L57-L60

The C++ constructor just copies the data, regardless of what size it is, meaning you can get arrays of less than 9 elements.
https://github.com/theochem/cellcutoff/blob/67205f0c85ac585c44fc738fcbd7bd9af2f0d7e9/cellcutoff/cell.cpp#L41

**Comment by tovrstra** [comment]
I should check again. There are two ways to implement `nvec<3`. one is by adding vectors orthogonal to periodic cell vectors to obtain an invertible 3x3 matrix. The other is to just store only the periodic vectors. I might have mixed up the two.

**Comment by tovrstra** [comment]
@matt-chan The public C++ constructor always creates 3 vectors. When it does not receive 3, the new ones are orthogonal to the given ones and have length 1. After that, the rest of the code can safely assume vecs and gvecs contain 9 elements. The private constructor was wrong: the arrays it copies always have the same size, irrespective of the `nvec` value. This is fixed in #34 and unit tests were added that fail with the old code.
